version: "3.7"
services:
  mysql:
    container_name: credens_mysql
    build:
      context: dockers/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: credens_mysql
      MYSQL_USER: credens
      MYSQL_PASSWORD: secret
    volumes:
      - "./var/dockers/db/mysql/data/:/var/lib/mysql"
      - "./var/dockers/db/mysql/log/:/var/log"
  rabbitmq:
    container_name: credens_rabbitmq
    build:
      context: dockers/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./var/dockers/amqp/rabbitmq/data/:/var/lib/rabbitmq/"
      - "./var/dockers/amqp/rabbitmq/log/:/var/log/rabbitmq/"
networks:
  default:
    external:
      name: credens_go_network