version: "3.7"
services:
  mysql:
    container_name: credens_mysql
    build:
      context: dockers/mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: credens_mysql
      MYSQL_USER: credens
      MYSQL_PASSWORD: secret
    volumes:
      - "./builds/docker/mysql:/var/lib/mysql"
      - "./builds/docker/mysql:/var/log"
networks:
    default:
      external:
        name: credens_go_network