version: "3.7"
services:
  mysql:
    container_name: credens_mysql
    build:
      context: dockers/mysql
    ports:
      - "3333:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./var/dockers/db/mysql:/var/lib/mysql"
      - "./var/dockers/db/mysql:/var/log"
networks:
    default:
      external:
        name: credens_go_network